# <center><font size = 6.5>P2P网络贷款数据表的分析_____Pandas统计分析基础

# <center><font size = 6.5>摘要

随着科技的发展和经济的充分发展，不仅出现了网络平台和网络贷款，而且人们对贷款的需求越来越强，当然不良的网络贷款带来严重的社会问题（扰乱治安等），因此对p2p网络贷款的分析，了解P2P网络贷款的数量特征是至关重要的，对P2P网络贷款数据的充分分析，可以为我国经济，统计，公安部门等相关部门提供参考依据，有相当重要的社会和时代意义，本文的P2P网络贷款数据表存放了网贷用户的基本信息（登录时间，更新时间，登录地点，登陆者账号名，借款规模，还款规模），揭示了数据的整体分布，数据的类属关系和数据之间的关联

关键字：P2P网络贷款数据 数据分析

# <center><font size = 6.5> 一.项目概述

根据所给的P2P贷款数据，网贷用户的基本信息，用户登陆时间更新时间借款成交时间，以及这些时间的时间差揭示网络贷款不同用户的行为信息。

# <center><font size = 6.5>二.数据初步提取和查看

In [81]:
from sqlalchemy import create_engine
import pandas as pd
# engine = create_engine('mysql+pymysql://root:1234@127.0.0.1:\3306/testdb?charset=utf8')
#先读取三张数据表的内容，先看个究竟
order1 = pd.read_csv('D:/Desktop/data/Training_LogInfo.csv',encoding='gbk')
#用户登录信息表(时间)
order2 = pd.read_csv('D:/Desktop/data/Training_Master.csv',encoding='gbk')
#用户登录信息表(地点)
order3 = pd.read_csv('D:/Desktop/data/Training_Userupdate.csv',encoding='gbk')
#信息更新表

# <center><font size=6.5>实训1

In [82]:
#掌握csv数据读取方法，掌握dataframe常用属性和方法，掌握pandas描述性统计方法
#本文的P2P网络贷款数据表存放了网贷用户的基本信息（。。。。。。），揭示了数据的整体分布，数据的类属关系和数据之间的关联
#用ndim,shape,memory_usage属性分别查看order1，order2 ,order3的维度，大小，占用内存信息
print(order1.ndim,order1.shape,order1.memory_usage)
#假设Listinginfo1是第二次登陆时间，LogInfo1是存贷款情况，LogInfo2是存款利息，LogInfo3是前次登陆时间

2 (580551, 5) <bound method DataFrame.memory_usage of           Idx Listinginfo1  LogInfo1  LogInfo2    LogInfo3
0       10001   2014-03-05       107         6  2014-02-20
1       10001   2014-03-05       107         6  2014-02-23
2       10001   2014-03-05       107         6  2014-02-24
3       10001   2014-03-05       107         6  2014-02-25
4       10001   2014-03-05       107         6  2014-02-27
5       10001   2014-03-05       107         6  2014-03-04
6       10001   2014-03-05         1         1  2014-02-20
7       10001   2014-03-05         1        20  2014-02-20
8       10001   2014-03-05        12         0  2014-02-20
9       10001   2014-03-05         1         2  2014-02-20
10      10001   2014-03-05         2         1  2014-02-20
11      10001   2014-03-05         4         1  2014-02-20
12      10001   2014-03-05        -4         6  2014-02-20
13      10001   2014-03-05        -4         6  2014-02-20
14      10001   2014-03-05        -4         6  2014-02-23
15      10001   2014-03-05        -4         6  2014-02-24
16      10001   2014-03-05        -4         6  2014-02-25
17      10001   2014-03-05        -4         6  2014-02-27
18      10001   2014-03-05        -4         6  2014-03-04
19      10002   2014-02-26        10         0  2013-06-21
20      10002   2014-02-26       107         6  2013-07-08
21      10002   2014-02-26       107         6  2013-07-08
22      10002   2014-02-26         1         1  2013-06-21
23      10002   2014-02-26         1         2  2014-02-20
24      10002   2014-02-26         1         6  2013-06-21
25      10002   2014-02-26         2         1  2013-06-21
26      10002   2014-02-26         4         1  2013-06-21
27      10002   2014-02-26         4        19  2013-07-08
28      10002   2014-02-26        -4         6  2014-02-20
29      10002   2014-02-26        -4         6  2014-02-25
...       ...          ...       ...       ...         ...
580521   9997   2014-02-28       107         6  2014-02-20
580522   9997   2014-02-28       107         6  2014-02-21
580523   9997   2014-02-28       107         6  2014-02-24
580524   9997   2014-02-28       107         6  2014-02-26
580525   9997   2014-02-28       107         6  2014-02-27
580526   9997   2014-02-28       107         6  2014-02-28
580527   9997   2014-02-28         1         1  2014-02-20
580528   9997   2014-02-28         1        20  2014-02-20
580529   9997   2014-02-28        12         0  2014-02-20
580530   9997   2014-02-28         1         2  2014-02-20
580531   9997   2014-02-28         2         1  2014-02-20
580532   9997   2014-02-28         4         1  2014-02-20
580533   9997   2014-02-28        -4         6  2014-02-20
580534   9997   2014-02-28        -4         6  2014-02-20
580535   9997   2014-02-28        -4         6  2014-02-20
580536   9997   2014-02-28        -4         6  2014-02-21
580537   9997   2014-02-28        -4         6  2014-02-24
580538   9997   2014-02-28        -4         6  2014-02-26
580539   9997   2014-02-28        -4         6  2014-02-27
580540   9997   2014-02-28        -4         6  2014-02-27
580541   9997   2014-02-28        -4         6  2014-02-28
580542   9998   2014-03-05         1         0  2014-02-20
580543   9998   2014-03-05         1         1  2014-02-20
580544   9998   2014-03-05         1        20  2014-02-20
580545   9998   2014-03-05         1         2  2014-02-20
580546   9998   2014-03-05         2         1  2014-02-20
580547   9998   2014-03-05         4         1  2014-02-20
580548   9998   2014-03-05        -4         6  2014-02-20
580549   9998   2014-03-05        -4         6  2014-03-05
580550   9998   2014-03-05         4         7  2014-03-05

[580551 rows x 5 columns]>

In [83]:
print(order2.ndim,order2.shape,order2.memory_usage)
#假设UserInfo_1是借款申请时间（月），UserInfo_2是申请借款地点，UserInfo_3是借款审批间隔时间（日）
#UserInfo_4是借款成交地点，WeblogInfo_1是借款成交时间（日）

2 (30000, 228) <bound method DataFrame.memory_usage of          Idx  UserInfo_1  UserInfo_2  UserInfo_3  UserInfo_4  WeblogInfo_1  \
0      10001         1.0          深圳         4.0          深圳           NaN
1      10002         1.0          温州         4.0          温州           NaN
2      10003         1.0          宜昌         3.0          宜昌           NaN
3      10006         4.0          南平         1.0          南平           NaN
4      10007         5.0          辽阳         1.0          辽阳           NaN
5      10008         1.0          吴忠         5.0          银川           NaN
6      10011         1.0          绵阳         3.0          赤峰           NaN
7      10015         4.0          东莞         5.0          东莞           NaN
8      10019         1.0          赤峰         6.0          赤峰           NaN
9      10021         3.0          武汉         5.0          鄂州           NaN
10     10022         5.0          武汉         5.0          武汉           NaN
11     10024         5.0          长沙         5.0          长沙           NaN
12     10026         3.0          漳州         3.0          漳州           NaN
13     10027         3.0         牡丹江         6.0         牡丹江           NaN
14     10031         1.0          太原         3.0          太原           NaN
15     10032         1.0          北京         6.0          北京           NaN
16     10036         1.0          成都         3.0          忻州           NaN
17     10039         1.0          三明         4.0          三明           NaN
18     10040         1.0          临沂         6.0          临沂           NaN
19     10044         4.0          临沂         6.0          临沂           NaN
20     10050         1.0          福州         5.0          福州           NaN
21     10054         4.0          泰州         4.0          泰州           NaN
22     10059         5.0          成都         4.0          大同           NaN
23      1006         4.0          上海         5.0          上海           NaN
24     10063         1.0  红河哈尼族彝族自治州         5.0  红河哈尼族彝族自治州           NaN
25     10067         4.0          南平         4.0          南平           NaN
26     10068         1.0          郴州         5.0          郴州           NaN
27     10069         3.0          常州         4.0          常州           NaN
28      1007         6.0          湖州         6.0          湖州           NaN
29     10070         4.0          茂名         1.0          佛山           NaN
...      ...         ...         ...         ...         ...           ...
29970   9905         1.0          咸宁         4.0          温州           NaN
29971    991         1.0          惠州         4.0          揭阳           NaN
29972   9912         1.0          温州         5.0          温州           NaN
29973   9914         3.0          常德         5.0          常德           NaN
29974   9918         3.0          赣州         1.0          东莞           NaN
29975   9919         5.0          镇江         3.0          镇江           NaN
29976    992         5.0          淮安         3.0          上海           NaN
29977   9921         6.0          福州         6.0          福州           NaN
29978   9923         5.0          三明         6.0          三明           NaN
29979   9926         1.0          深圳         5.0          东莞           NaN
29980   9935         1.0         NaN         4.0         NaN           NaN
29981   9936         5.0          惠州         1.0          深圳           NaN
29982   9938         1.0          泉州         6.0          泉州           NaN
29983   9941         1.0          衡阳         6.0          广州           NaN
29984   9952         1.0     临夏回族自治州         3.0     临夏回族自治州           NaN
29985   9964         1.0          南昌         4.0          深圳           NaN
29986   9966         1.0          佛山         3.0         NaN           NaN
29987   9967         7.0          扬州         5.0          扬州           NaN
29988   9974         1.0          荆门         6.0          荆门           NaN
29989   9979         4.0          青岛         5.0          青岛           NaN
29990   9983         6.0          上海         5.0          上海           NaN
29991   9984         4.0          晋中         4.0          晋中           NaN
29992   9986         1.0          运城         5.0          运城           NaN
29993   9989         1.0          北京         3.0          北京           NaN
29994   9990         4.0          酒泉         6.0         嘉峪关           NaN
29995   9991         3.0          南阳         4.0          南阳           NaN
29996   9992         3.0          宁德         4.0          泉州           NaN
29997   9995         1.0          天津         2.0          天津           NaN
29998   9997         3.0          运城         3.0          运城           NaN
29999   9998         4.0          金华         5.0          无锡           NaN

       WeblogInfo_2  WeblogInfo_3  WeblogInfo_4  WeblogInfo_5  ...  \
0               1.0           NaN           1.0           1.0  ...
1               0.0           NaN           1.0           1.0  ...
2               0.0           NaN           2.0           2.0  ...
3               NaN           NaN           NaN           NaN  ...
4               0.0           NaN           1.0           1.0  ...
5               0.0           NaN           2.0           2.0  ...
6               0.0           NaN          13.0           1.0  ...
7               0.0           NaN          12.0           6.0  ...
8               0.0           NaN          10.0           6.0  ...
9               0.0           NaN           1.0           1.0  ...
10              0.0           NaN           3.0           2.0  ...
11              1.0           NaN           1.0           1.0  ...
12              1.0           NaN          11.0           3.0  ...
13              0.0           NaN           1.0           1.0  ...
14              0.0           NaN           3.0           1.0  ...
15              0.0           NaN           2.0           2.0  ...
16              0.0           NaN           4.0           3.0  ...
17              0.0           NaN           4.0           2.0  ...
18              0.0           NaN           1.0           1.0  ...
19              0.0           NaN           2.0           2.0  ...
20              0.0           NaN           3.0           2.0  ...
21              0.0           NaN           3.0           2.0  ...
22              0.0           NaN           8.0           8.0  ...
23              1.0           NaN           1.0           1.0  ...
24              0.0           NaN           1.0           1.0  ...
25              0.0           NaN           2.0           1.0  ...
26              0.0           NaN           9.0           5.0  ...
27              0.0           NaN           2.0           2.0  ...
28              0.0           NaN           2.0           2.0  ...
29              0.0           NaN           2.0           1.0  ...
...             ...           ...           ...           ...  ...
29970           0.0           NaN           2.0           1.0  ...
29971           1.0           NaN           8.0           3.0  ...
29972           0.0           NaN           5.0           5.0  ...
29973           0.0           NaN           6.0           1.0  ...
29974           0.0           NaN          13.0          11.0  ...
29975           0.0           NaN           8.0           1.0  ...
29976           0.0           NaN           3.0           2.0  ...
29977           0.0           NaN           1.0           1.0  ...
29978           1.0           NaN           6.0           3.0  ...
29979           0.0           NaN           4.0           3.0  ...
29980           0.0           NaN           1.0           1.0  ...
29981           0.0           NaN           4.0           4.0  ...
29982           0.0           NaN           3.0           1.0  ...
29983           0.0           NaN           2.0           2.0  ...
29984           0.0           NaN           2.0           1.0  ...
29985           1.0           NaN           2.0           2.0  ...
29986           0.0           NaN           3.0           1.0  ...
29987           0.0           NaN           5.0           3.0  ...
29988           0.0           NaN           1.0           1.0  ...
29989           0.0           NaN          12.0           3.0  ...
29990           1.0           NaN           2.0           2.0  ...
29991           0.0           NaN           7.0           2.0  ...
29992           0.0           NaN           3.0           3.0  ...
29993           0.0           NaN           5.0           4.0  ...
29994           NaN           NaN           NaN           NaN  ...
29995           1.0           NaN           3.0           2.0  ...
29996           0.0           NaN           6.0           1.0  ...
29997           0.0           NaN           2.0           2.0  ...
29998           0.0           NaN           1.0           1.0  ...
29999           0.0           NaN           1.0           1.0  ...

       SocialNetwork_10  SocialNetwork_11  SocialNetwork_12  SocialNetwork_13  \
0                   222                -1                 0                 0
1                     1                -1                 0                 0
2                    -1                -1                -1                 1
3                    -1                -1                -1                 0
4                    -1                -1                -1                 0
5                    -1                -1                -1                 0
6                    14                -1                 0                 1
7                   559                -1                 0                 1
8                    -1                -1                -1                 0
9                    -1                -1                -1                 1
10                   -1                -1                -1                 0
11                   -1                -1                -1                 0
12                  111                -1                 0                 1
13                   -1                -1                -1                 0
14                  572                -1                 0                 1
15                   88                -1                 0                 1
16                   -1                -1                -1                 0
17                  105                -1                 0                 0
18                   -1                -1                -1                 0
19                   -1                -1                -1                 0
20                  250                -1                 0                 1
21                   18                -1                 0                 0
22                   52                -1                 0                 1
23                  452                -1                 0                 0
24                   -1                -1                -1                 1
25                   37                -1                 0                 1
26                   85                -1                 0                 0
27                  112                -1                 0                 0
28                   -1                -1                -1                 0
29                   -1                -1                -1                 0
...                 ...               ...               ...               ...
29970                -1                -1                -1                 0
29971                -1                -1                -1                 0
29972               318                -1                 0                 0
29973                -1                -1                -1                 0
29974               194                -1                 0                 1
29975                38                -1                 0                 0
29976                -1                -1                -1                 1
29977                -1                -1                -1                 0
29978                -1                -1                -1                 0
29979                -1                -1                -1                 0
29980                -1                -1                -1                 0
29981                -1                -1                -1                 0
29982                 5                -1                 0                 1
29983                -1                -1                -1                 0
29984                -1                -1                -1                 1
29985                 1                -1                 0                 1
29986                -1                -1                -1                 0
29987                -1                -1                -1                 1
29988                -1                -1                -1                 0
29989                15                -1                 0                 1
29990               640                -1                 0                 1
29991               230                -1                 0                 0
29992                -1                -1                -1                 0
29993                -1                -1                -1                 1
29994                -1                -1                -1                 0
29995                 0                -1                 0                 1
29996               407                -1                 0                 0
29997                -1                -1                -1                 0
29998               612                -1                 0                 1
29999                -1                -1                -1                 0

       SocialNetwork_14  SocialNetwork_15  SocialNetwork_16  SocialNetwork_17  \
0                     0                 0                 0                 1
1                     0                 0                 0                 2
2                     0                 0                 0                 0
3                     0                 0                 0                 0
4                     0                 0                 0                 0
5                     0                 0                 0                 0
6                     0                 0                 0                 1
7                     0                 0                 0                 1
8                     0                 0                 1                 0
9                     0                 0                 0                 0
10                    0                 0                 0                 0
11                    0                 0                 0                 0
12                    0                 0                 0                 1
13                    0                 0                 0                 0
14                    0                 0                 0                 1
15                    1                 0                 0                 1
16                    0                 0                 0                 0
17                    0                 0                 0                 1
18                    0                 0                 0                 0
19                    0                 0                 0                 0
20                    1                 0                 0                 1
21                    0                 0                 0                 1
22                    0                 0                 0                 1
23                    0                 0                 0                 1
24                    1                 0                 0                 0
25                    0                 0                 0                 1
26                    1                 0                 0                 1
27                    0                 0                 0                 1
28                    0                 1                 0                 0
29                    0                 0                 0                 0
...                 ...               ...               ...               ...
29970                 0                 0                 0                 0
29971                 0                 0                 0                 0
29972                 0                 0                 0                 1
29973                 0                 0                 0                 0
29974                 1                 0                 0                 1
29975                 0                 0                 0                 1
29976                 0                 0                 0                 0
29977                 0                 0                 0                 0
29978                 0                 0                 0                 0
29979                 0                 0                 0                 0
29980                 0                 0                 0                 0
29981                 0                 0                 0                 0
29982                 1                 0                 0                 1
29983                 0                 0                 0                 0
29984                 0                 0                 0                 0
29985                 0                 0                 0                 1
29986                 0                 0                 0                 0
29987                 0                 0                 0                 0
29988                 0                 0                 0                 0
29989                 0                 1                 0                 1
29990                 0                 0                 0                 1
29991                 0                 0                 0                 1
29992                 0                 0                 0                 0
29993                 0                 0                 0                 0
29994                 0                 0                 0                 0
29995                 0                 0                 0                 1
29996                 0                 0                 0                 1
29997                 0                 0                 0                 0
29998                 0                 0                 0                 1
29999                 0                 0                 0                 0

       target  ListingInfo
0           0     2014/3/5
1           0    2014/2/26
2           0    2014/2/28
3           0    2014/2/25
4           0    2014/2/27
5           0    2014/2/27
6           1    2014/2/24
7           0    2014/2/28
8           1    2014/2/24
9           0    2014/2/27
10          0    2014/2/25
11          0     2014/3/6
12          0     2014/3/4
13          1    2014/2/26
14          0     2014/3/7
15          0    2014/2/26
16          0    2014/2/27
17          0    2014/2/22
18          1    2014/2/23
19          0    2014/2/24
20          0    2014/2/26
21          0    2014/2/24
22          0    2014/2/26
23          0   2013/11/18
24          0    2014/2/22
25          0    2014/2/25
26          0     2014/3/4
27          0    2014/2/24
28          0   2013/11/18
29          0     2014/3/3
...       ...          ...
29970       0     2014/3/4
29971       0   2013/11/21
29972       0     2014/3/5
29973       0     2014/3/7
29974       0    2014/2/20
29975       0    2014/2/28
29976       0   2013/11/15
29977       0    2014/2/26
29978       0    2014/3/10
29979       0    2014/2/21
29980       0    2014/2/24
29981       0    2014/2/27
29982       0    2014/2/24
29983       1    2014/2/21
29984       0    2014/2/22
29985       0    2014/2/21
29986       0    2014/2/23
29987       0    2014/2/24
29988       0    2014/2/28
29989       0    2014/2/24
29990       0    2014/2/25

In [84]:
print(order3.ndim,order3.shape,order3.memory_usage)
#假设ListingInfo1是用户信息更新时间，UserupdateInfo1是用户账号，UserInfo_3是上一次用户登陆时间

2 (372463, 4) <bound method DataFrame.memory_usage of           Idx ListingInfo1    UserupdateInfo1 UserupdateInfo2
0       10001   2014/03/05       _EducationId      2014/02/20
1       10001   2014/03/05         _HasBuyCar      2014/02/20
2       10001   2014/03/05    _LastUpdateDate      2014/02/20
3       10001   2014/03/05  _MarriageStatusId      2014/02/20
4       10001   2014/03/05       _MobilePhone      2014/02/20
5       10001   2014/03/05       _MobilePhone      2014/02/20
6       10001   2014/03/05                _QQ      2014/02/20
7       10001   2014/03/05  _ResidenceAddress      2014/02/20
8       10001   2014/03/05    _ResidencePhone      2014/02/20
9       10001   2014/03/05   _ResidenceTypeId      2014/02/20
10      10001   2014/03/05    _ResidenceYears      2014/02/20
11      10002   2014/02/26               _age      2013/06/21
12      10002   2014/02/26       _educationId      2013/06/21
13      10002   2014/02/26            _gender      2013/06/21
14      10002   2014/02/26         _hasBuyCar      2013/06/21
15      10002   2014/02/26          _idNumber      2013/06/21
16      10002   2014/02/26    _lastUpdateDate      2013/06/21
17      10002   2014/02/26    _lastUpdateDate      2013/07/08
18      10002   2014/02/26    _lastUpdateDate      2013/07/08
19      10002   2014/02/26    _lastUpdateDate      2013/07/08
20      10002   2014/02/26    _lastUpdateDate      2013/07/08
21      10002   2014/02/26  _marriageStatusId      2013/06/21
22      10002   2014/02/26       _mobilePhone      2013/06/21
23      10002   2014/02/26       _MobilePhone      2014/02/20
24      10002   2014/02/26                _qQ      2013/06/21
25      10002   2014/02/26          _realName      2013/06/21
26      10002   2014/02/26         _regStepId      2013/06/21
27      10002   2014/02/26         _regStepId      2013/06/21
28      10002   2014/02/26  _residenceAddress      2013/06/21
29      10002   2014/02/26    _residencePhone      2013/06/21
...       ...          ...                ...             ...
372433   9995   2014/02/24       _EducationId      2014/02/20
372434   9995   2014/02/24         _HasBuyCar      2014/02/20
372435   9995   2014/02/24  _MarriageStatusId      2014/02/20
372436   9995   2014/02/24       _MobilePhone      2014/02/20
372437   9995   2014/02/24                _QQ      2014/02/20
372438   9995   2014/02/24  _ResidenceAddress      2014/02/20
372439   9995   2014/02/24    _ResidencePhone      2014/02/20
372440   9995   2014/02/24   _ResidenceTypeId      2014/02/20
372441   9995   2014/02/24    _ResidenceYears      2014/02/20
372442   9997   2014/02/28       _EducationId      2014/02/20
372443   9997   2014/02/28         _HasBuyCar      2014/02/20
372444   9997   2014/02/28  _MarriageStatusId      2014/02/20
372445   9997   2014/02/28       _MobilePhone      2014/02/20
372446   9997   2014/02/28       _MobilePhone      2014/02/20
372447   9997   2014/02/28                _QQ      2014/02/20
372448   9997   2014/02/28  _ResidenceAddress      2014/02/20
372449   9997   2014/02/28    _ResidencePhone      2014/02/20
372450   9997   2014/02/28   _ResidenceTypeId      2014/02/20
372451   9997   2014/02/28    _ResidenceYears      2014/02/20
372452   9998   2014/03/05       _EducationId      2014/02/20
372453   9998   2014/03/05       _EducationId      2014/02/20
372454   9998   2014/03/05         _HasBuyCar      2014/02/20
372455   9998   2014/03/05  _MarriageStatusId      2014/02/20
372456   9998   2014/03/05       _MobilePhone      2014/02/20
372457   9998   2014/03/05       _MobilePhone      2014/02/20
372458   9998   2014/03/05                _QQ      2014/02/20
372459   9998   2014/03/05  _ResidenceAddress      2014/02/20
372460   9998   2014/03/05    _ResidencePhone      2014/02/20
372461   9998   2014/03/05   _ResidenceTypeId      2014/02/20
372462   9998   2014/03/05    _ResidenceYears      2014/02/20

[372463 rows x 4 columns]>

In [85]:
#对多列的描述性统计
print('描述性统计为: \n',order1.loc[:,['Idx','LogInfo1','LogInfo2','Listinginfo1','LogInfo3']].describe)

描述性统计为:
 <bound method NDFrame.describe of           Idx  LogInfo1  LogInfo2 Listinginfo1    LogInfo3
0       10001       107         6   2014-03-05  2014-02-20
1       10001       107         6   2014-03-05  2014-02-23
2       10001       107         6   2014-03-05  2014-02-24
3       10001       107         6   2014-03-05  2014-02-25
4       10001       107         6   2014-03-05  2014-02-27
5       10001       107         6   2014-03-05  2014-03-04
6       10001         1         1   2014-03-05  2014-02-20
7       10001         1        20   2014-03-05  2014-02-20
8       10001        12         0   2014-03-05  2014-02-20
9       10001         1         2   2014-03-05  2014-02-20
10      10001         2         1   2014-03-05  2014-02-20
11      10001         4         1   2014-03-05  2014-02-20
12      10001        -4         6   2014-03-05  2014-02-20
13      10001        -4         6   2014-03-05  2014-02-20
14      10001        -4         6   2014-03-05  2014-02-23
15      10001        -4         6   2014-03-05  2014-02-24
16      10001        -4         6   2014-03-05  2014-02-25
17      10001        -4         6   2014-03-05  2014-02-27
18      10001        -4         6   2014-03-05  2014-03-04
19      10002        10         0   2014-02-26  2013-06-21
20      10002       107         6   2014-02-26  2013-07-08
21      10002       107         6   2014-02-26  2013-07-08
22      10002         1         1   2014-02-26  2013-06-21
23      10002         1         2   2014-02-26  2014-02-20
24      10002         1         6   2014-02-26  2013-06-21
25      10002         2         1   2014-02-26  2013-06-21
26      10002         4         1   2014-02-26  2013-06-21
27      10002         4        19   2014-02-26  2013-07-08
28      10002        -4         6   2014-02-26  2014-02-20
29      10002        -4         6   2014-02-26  2014-02-25
...       ...       ...       ...          ...         ...
580521   9997       107         6   2014-02-28  2014-02-20
580522   9997       107         6   2014-02-28  2014-02-21
580523   9997       107         6   2014-02-28  2014-02-24
580524   9997       107         6   2014-02-28  2014-02-26
580525   9997       107         6   2014-02-28  2014-02-27
580526   9997       107         6   2014-02-28  2014-02-28
580527   9997         1         1   2014-02-28  2014-02-20
580528   9997         1        20   2014-02-28  2014-02-20
580529   9997        12         0   2014-02-28  2014-02-20
580530   9997         1         2   2014-02-28  2014-02-20
580531   9997         2         1   2014-02-28  2014-02-20
580532   9997         4         1   2014-02-28  2014-02-20
580533   9997        -4         6   2014-02-28  2014-02-20
580534   9997        -4         6   2014-02-28  2014-02-20
580535   9997        -4         6   2014-02-28  2014-02-20
580536   9997        -4         6   2014-02-28  2014-02-21
580537   9997        -4         6   2014-02-28  2014-02-24
580538   9997        -4         6   2014-02-28  2014-02-26
580539   9997        -4         6   2014-02-28  2014-02-27
580540   9997        -4         6   2014-02-28  2014-02-27
580541   9997        -4         6   2014-02-28  2014-02-28
580542   9998         1         0   2014-03-05  2014-02-20
580543   9998         1         1   2014-03-05  2014-02-20
580544   9998         1        20   2014-03-05  2014-02-20
580545   9998         1         2   2014-03-05  2014-02-20
580546   9998         2         1   2014-03-05  2014-02-20
580547   9998         4         1   2014-03-05  2014-02-20
580548   9998        -4         6   2014-03-05  2014-02-20
580549   9998        -4         6   2014-03-05  2014-03-05
580550   9998         4         7   2014-03-05  2014-03-05

[580551 rows x 5 columns]>

In [86]:
print('描述性统计为: \n',order2.loc[:,['Idx','UserInfo_1','UserInfo_2','UserInfo_3','UserInfo_','WeblogInfo_1']].describe)

描述性统计为:
 <bound method NDFrame.describe of          Idx  UserInfo_1  UserInfo_2  UserInfo_3  UserInfo_  WeblogInfo_1
0      10001         1.0          深圳         4.0        NaN           NaN
1      10002         1.0          温州         4.0        NaN           NaN
2      10003         1.0          宜昌         3.0        NaN           NaN
3      10006         4.0          南平         1.0        NaN           NaN
4      10007         5.0          辽阳         1.0        NaN           NaN
5      10008         1.0          吴忠         5.0        NaN           NaN
6      10011         1.0          绵阳         3.0        NaN           NaN
7      10015         4.0          东莞         5.0        NaN           NaN
8      10019         1.0          赤峰         6.0        NaN           NaN
9      10021         3.0          武汉         5.0        NaN           NaN
10     10022         5.0          武汉         5.0        NaN           NaN
11     10024         5.0          长沙         5.0        NaN           NaN
12     10026         3.0          漳州         3.0        NaN           NaN
13     10027         3.0         牡丹江         6.0        NaN           NaN
14     10031         1.0          太原         3.0        NaN           NaN
15     10032         1.0          北京         6.0        NaN           NaN
16     10036         1.0          成都         3.0        NaN           NaN
17     10039         1.0          三明         4.0        NaN           NaN
18     10040         1.0          临沂         6.0        NaN           NaN
19     10044         4.0          临沂         6.0        NaN           NaN
20     10050         1.0          福州         5.0        NaN           NaN
21     10054         4.0          泰州         4.0        NaN           NaN
22     10059         5.0          成都         4.0        NaN           NaN
23      1006         4.0          上海         5.0        NaN           NaN
24     10063         1.0  红河哈尼族彝族自治州         5.0        NaN           NaN
25     10067         4.0          南平         4.0        NaN           NaN
26     10068         1.0          郴州         5.0        NaN           NaN
27     10069         3.0          常州         4.0        NaN           NaN
28      1007         6.0          湖州         6.0        NaN           NaN
29     10070         4.0          茂名         1.0        NaN           NaN
...      ...         ...         ...         ...        ...           ...
29970   9905         1.0          咸宁         4.0        NaN           NaN
29971    991         1.0          惠州         4.0        NaN           NaN
29972   9912         1.0          温州         5.0        NaN           NaN
29973   9914         3.0          常德         5.0        NaN           NaN
29974   9918         3.0          赣州         1.0        NaN           NaN
29975   9919         5.0          镇江         3.0        NaN           NaN
29976    992         5.0          淮安         3.0        NaN           NaN
29977   9921         6.0          福州         6.0        NaN           NaN
29978   9923         5.0          三明         6.0        NaN           NaN
29979   9926         1.0          深圳         5.0        NaN           NaN
29980   9935         1.0         NaN         4.0        NaN           NaN
29981   9936         5.0          惠州         1.0        NaN           NaN
29982   9938         1.0          泉州         6.0        NaN           NaN
29983   9941         1.0          衡阳         6.0        NaN           NaN
29984   9952         1.0     临夏回族自治州         3.0        NaN           NaN
29985   9964         1.0          南昌         4.0        NaN           NaN
29986   9966         1.0          佛山         3.0        NaN           NaN
29987   9967         7.0          扬州         5.0        NaN           NaN
29988   9974         1.0          荆门         6.0        NaN           NaN
29989   9979         4.0          青岛         5.0        NaN           NaN
29990   9983         6.0          上海         5.0        NaN           NaN
29991   9984         4.0          晋中         4.0        NaN           NaN
29992   9986         1.0          运城         5.0        NaN           NaN
29993   9989         1.0          北京         3.0        NaN           NaN
29994   9990         4.0          酒泉         6.0        NaN           NaN
29995   9991         3.0          南阳         4.0        NaN           NaN
29996   9992         3.0          宁德         4.0        NaN           NaN
29997   9995         1.0          天津         2.0        NaN           NaN
29998   9997         3.0          运城         3.0        NaN           NaN
29999   9998         4.0          金华         5.0        NaN           NaN

[30000 rows x 6 columns]>

In [88]:
print('描述性统计为: \n',order3.loc[:,['Idx','ListingInfo1','UserupdateInfo1','UserupdateInfo2']].describe)

描述性统计为:
 <bound method NDFrame.describe of           Idx ListingInfo1    UserupdateInfo1 UserupdateInfo2
0       10001   2014/03/05       _EducationId      2014/02/20
1       10001   2014/03/05         _HasBuyCar      2014/02/20
2       10001   2014/03/05    _LastUpdateDate      2014/02/20
3       10001   2014/03/05  _MarriageStatusId      2014/02/20
4       10001   2014/03/05       _MobilePhone      2014/02/20
5       10001   2014/03/05       _MobilePhone      2014/02/20
6       10001   2014/03/05                _QQ      2014/02/20
7       10001   2014/03/05  _ResidenceAddress      2014/02/20
8       10001   2014/03/05    _ResidencePhone      2014/02/20
9       10001   2014/03/05   _ResidenceTypeId      2014/02/20
10      10001   2014/03/05    _ResidenceYears      2014/02/20
11      10002   2014/02/26               _age      2013/06/21
12      10002   2014/02/26       _educationId      2013/06/21
13      10002   2014/02/26            _gender      2013/06/21
14      10002   2014/02/26         _hasBuyCar      2013/06/21
15      10002   2014/02/26          _idNumber      2013/06/21
16      10002   2014/02/26    _lastUpdateDate      2013/06/21
17      10002   2014/02/26    _lastUpdateDate      2013/07/08
18      10002   2014/02/26    _lastUpdateDate      2013/07/08
19      10002   2014/02/26    _lastUpdateDate      2013/07/08
20      10002   2014/02/26    _lastUpdateDate      2013/07/08
21      10002   2014/02/26  _marriageStatusId      2013/06/21
22      10002   2014/02/26       _mobilePhone      2013/06/21
23      10002   2014/02/26       _MobilePhone      2014/02/20
24      10002   2014/02/26                _qQ      2013/06/21
25      10002   2014/02/26          _realName      2013/06/21
26      10002   2014/02/26         _regStepId      2013/06/21
27      10002   2014/02/26         _regStepId      2013/06/21
28      10002   2014/02/26  _residenceAddress      2013/06/21
29      10002   2014/02/26    _residencePhone      2013/06/21
...       ...          ...                ...             ...
372433   9995   2014/02/24       _EducationId      2014/02/20
372434   9995   2014/02/24         _HasBuyCar      2014/02/20
372435   9995   2014/02/24  _MarriageStatusId      2014/02/20
372436   9995   2014/02/24       _MobilePhone      2014/02/20
372437   9995   2014/02/24                _QQ      2014/02/20
372438   9995   2014/02/24  _ResidenceAddress      2014/02/20
372439   9995   2014/02/24    _ResidencePhone      2014/02/20
372440   9995   2014/02/24   _ResidenceTypeId      2014/02/20
372441   9995   2014/02/24    _ResidenceYears      2014/02/20
372442   9997   2014/02/28       _EducationId      2014/02/20
372443   9997   2014/02/28         _HasBuyCar      2014/02/20
372444   9997   2014/02/28  _MarriageStatusId      2014/02/20
372445   9997   2014/02/28       _MobilePhone      2014/02/20
372446   9997   2014/02/28       _MobilePhone      2014/02/20
372447   9997   2014/02/28                _QQ      2014/02/20
372448   9997   2014/02/28  _ResidenceAddress      2014/02/20
372449   9997   2014/02/28    _ResidencePhone      2014/02/20
372450   9997   2014/02/28   _ResidenceTypeId      2014/02/20
372451   9997   2014/02/28    _ResidenceYears      2014/02/20
372452   9998   2014/03/05       _EducationId      2014/02/20
372453   9998   2014/03/05       _EducationId      2014/02/20
372454   9998   2014/03/05         _HasBuyCar      2014/02/20
372455   9998   2014/03/05  _MarriageStatusId      2014/02/20
372456   9998   2014/03/05       _MobilePhone      2014/02/20
372457   9998   2014/03/05       _MobilePhone      2014/02/20
372458   9998   2014/03/05                _QQ      2014/02/20
372459   9998   2014/03/05  _ResidenceAddress      2014/02/20
372460   9998   2014/03/05    _ResidencePhone      2014/02/20
372461   9998   2014/03/05   _ResidenceTypeId      2014/02/20
372462   9998   2014/03/05    _ResidenceYears      2014/02/20

[372463 rows x 4 columns]>

In [89]:
#用describe方法进行描述性统计，并且剔除相同或全为空的列
#假设Listinginfo1是第二次登陆时间，LogInfo1是存贷款情况，LogInfo2是存贷利息，LogInfo3是前次登陆时间
order1['Idx'].drop_duplicates
order1['LogInfo1'].drop_duplicates
order1['LogInfo2'].drop_duplicates
order1['LogInfo3'].drop_duplicates
order1['Listinginfo1'].drop_duplicates
print('''P2P网络贷款数据表的'Idx','LogInfo1','LogInfo2','Listinginfo1','LogInfo3'的描述性统计结果为： ''','\n',
      order1[['Idx','LogInfo1','LogInfo2','Listinginfo1','LogInfo3']].describe())
#账号是均匀分布的，存款的人挺少的，但是存了款的人存了挺多钱，4分之1的人欠了钱，大部分人所得利息为6元，也有人是23元，

P2P网络贷款数据表的'Idx','LogInfo1','LogInfo2','Listinginfo1','LogInfo3'的描述性统计结果为：
                  Idx       LogInfo1       LogInfo2
count  580551.000000  580551.000000  580551.000000
mean    44911.327794      11.760608       6.070486
std     26484.183832      63.741930       5.123067
min         3.000000     -10.000000       0.000000
25%     21450.000000      -4.000000       2.000000
50%     45325.000000       1.000000       6.000000
75%     67913.000000       2.000000       6.000000
max     91703.000000    3001.000000      23.000000

In [90]:
order2['Idx'].drop_duplicates
order2['UserInfo_1'].drop_duplicates
order2['UserInfo_2'].drop_duplicates
order2['UserInfo_3'].drop_duplicates
order2['UserInfo_4'].drop_duplicates
order2['WeblogInfo_1'].drop_duplicates
print('''P2P网络贷款数据表的'Idx','UserInfo_1','UserInfo_2','UserInfo_3','UserInfo_4','WeblogInfo_1'的描述性统计结果为： ''','\n',
      order2[['Idx','UserInfo_1','UserInfo_2','UserInfo_3','UserInfo_4','WeblogInfo_1']].describe())
#假设UserInfo_1是借款申请时间（月），UserInfo_2是申请借款地点，UserInfo_3是借款审批间隔时间（日）
#UserInfo_4是借款成交地点，WeblogInfo_1是借款成交时间（日）
#人们申请借款的时间分布是均匀的，借款审批间隔时间大部分是5天，最长7天

P2P网络贷款数据表的'Idx','UserInfo_1','UserInfo_2','UserInfo_3','UserInfo_4','WeblogInfo_1'的描述性统计结果为：
                 Idx    UserInfo_1    UserInfo_3  WeblogInfo_1
count  30000.000000  29994.000000  29993.000000    970.000000
mean   46318.673267      3.219911      4.694329      2.201031
std    26640.397805      1.827684      1.321458      7.831679
min        3.000000      0.000000      0.000000      1.000000
25%    22924.250000      1.000000      4.000000      1.000000
50%    46849.500000      3.000000      5.000000      1.000000
75%    69447.250000      5.000000      5.000000      1.000000
max    91703.000000      7.000000      7.000000    133.000000

In [91]:
order3['Idx'].drop_duplicates
order3['UserupdateInfo1'].drop_duplicates
order3['UserupdateInfo2'].drop_duplicates
order3['ListingInfo1'].drop_duplicates
print('''P2P网络贷款数据表的'Idx','ListingInfo1','UserupdateInfo1','UserupdateInfo2'的描述性统计结果为： ''','\n',
      order3[['Idx','ListingInfo1','UserupdateInfo1','UserupdateInfo2']].describe())

P2P网络贷款数据表的'Idx','ListingInfo1','UserupdateInfo1','UserupdateInfo2'的描述性统计结果为：
                  Idx
count  372463.000000
mean    44838.613344
std     26436.962709
min         3.000000
25%     22434.000000
50%     44394.000000
75%     67239.000000
max     91703.000000

# <center><font size=6.5>实训2

In [92]:
#掌握时间字符串和标准时间的转换方法
#掌握时间信息提取的方法
#掌握时间数据的算术运算
#需求背景说明
#用户信息更新表和登录信息表中均存在大量时间数据，提取时间数据内存在的信息，一方面可以加深对数据的理解另一方面能够探索这部分信息和目标的关联程
#度。同时用户登录时间借款成交时间，用户信息更新时间这些时间的时间差也能够反映出P2P网络贷款不同用户的行为信息。

In [93]:
#使用to_datetime函数转换用户信息更新表和登录信息表的时间字符串
print('进行转换前订单信息表Listinginfo1和LogInfo3的类型为： ',order1['LogInfo3'].dtypes,order1['Listinginfo1'].dtypes)

进行转换前订单信息表Listinginfo1和LogInfo3的类型为：  object object

In [94]:
order1['LogInfo3']=pd.to_datetime(order1['LogInfo3'])
order1['Listinginfo1']=pd.to_datetime(order1['Listinginfo1'])
print('进行转换后订单信息表Listinginfo1和LogInfo3的类型为： ',order1['LogInfo3'].dtypes,order1['Listinginfo1'].dtypes)

进行转换后订单信息表Listinginfo1和LogInfo3的类型为：  datetime64[ns] datetime64[ns]

In [95]:
order3['ListingInfo1'] = pd.to_datetime(order3['ListingInfo1'])
order3['UserupdateInfo2'] = pd.to_datetime(order3['UserupdateInfo2'])
order1['Listinginfo1'] = pd.to_datetime(order1['Listinginfo1'])
order1['LogInfo3'] = pd.to_datetime(order1['LogInfo3'])
#显示转换后的数据类型
print(order3['ListingInfo1'].dtypes)

datetime64[ns]

In [96]:
#使用year,month,week等方法提取用户信息更新表和登录信息表中的时间信息
year_1 = [i.year for i in order3['ListingInfo1']]
year_2 = [i.year for i in order3['UserupdateInfo2']]
year_3 = [i.year for i in order1['Listinginfo1']]
year_4 = [i.year for i in order1['LogInfo3']]
print('用户信息更新表中ListingInfo1的年份数据：',year_1[:5])
print('用户信息更新表中UserupdateInfo2的年份数据：',year_2[:5])
print('登录信息表中ListingInfo1的年份数据：',year_3[:5])
print('登录信息表中LogInfo3的年份数据：',year_4[:5])
#集中在2014年

用户信息更新表中ListingInfo1的年份数据： [2014, 2014, 2014, 2014, 2014]
用户信息更新表中UserupdateInfo2的年份数据： [2014, 2014, 2014, 2014, 2014]
登录信息表中ListingInfo1的年份数据： [2014, 2014, 2014, 2014, 2014]
登录信息表中LogInfo3的年份数据： [2014, 2014, 2014, 2014, 2014]

In [97]:
month_1 = [i.month for i in order3['ListingInfo1']]
month_2 = [i.month for i in order3['UserupdateInfo2']]
month_3 = [i.month for i in order1['Listinginfo1']]
month_4 = [i.month for i in order1['LogInfo3']]
print('用户信息更新表中ListingInfo1的月份数据：',month_1[:5])
print('用户信息更新表中UserupdateInfo2的月份数据：',month_2[:5])
print('登录信息表中ListingInfo1的月份数据：',month_3[:5])
print('登录信息表中LogInfo3的月份数据：',month_4[:5])

用户信息更新表中ListingInfo1的月份数据： [3, 3, 3, 3, 3]
用户信息更新表中UserupdateInfo2的月份数据： [2, 2, 2, 2, 2]
登录信息表中ListingInfo1的月份数据： [3, 3, 3, 3, 3]
登录信息表中LogInfo3的月份数据： [2, 2, 2, 2, 2]

In [98]:
week_1 = [i.week for i in order3['ListingInfo1']]
week_2 = [i.week for i in order3['UserupdateInfo2']]
week_3 = [i.week for i in order1['Listinginfo1']]
week_4 = [i.week for i in order1['LogInfo3']]
print('用户信息更新表ListingInfo1的一年中的第几周数据：',week_1[:5])
print('用户信息更新表UserupdateInfo2的一年中的第几周数据：',week_2[:5])
print('登录信息表ListingInfo1的一年中的第几周数据：',week_3[:5])
print('登录信息表LogInfo3的一年中的第几周数据：',week_4[:5])
#集中在第8，9，10周
#而且都是最近登陆时间是第10周，第一次更新都在第8周，第二次更新都在第10周

用户信息更新表ListingInfo1的一年中的第几周数据： [10, 10, 10, 10, 10]
用户信息更新表UserupdateInfo2的一年中的第几周数据： [8, 8, 8, 8, 8]
登录信息表ListingInfo1的一年中的第几周数据： [10, 10, 10, 10, 10]
登录信息表LogInfo3的一年中的第几周数据： [8, 8, 9, 9, 9]

In [99]:
day1 = pd.PeriodIndex(order3['ListingInfo1'],freq='D')
day2 = pd.PeriodIndex(order3['UserupdateInfo2'],freq='D')
day3 = pd.PeriodIndex(order1['Listinginfo1'],freq='D')
day4 = pd.PeriodIndex(order1['LogInfo3'],freq='D')
timedelta_D1= day1 - day2
timedelta_D2= day3 - day4
print('用户信息更新表中的时间差为：\n',timedelta_D1)
print('登录信息表中的时间差为：\n',timedelta_D2)
#时间差都是13天

用户信息更新表中的时间差为：
 Index([<13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>,
       <13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>,
       ...
       <13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>,
       <13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>],
      dtype='object', length=372463)
登录信息表中的时间差为：
 Index([<13 * Days>, <10 * Days>,  <9 * Days>,  <8 * Days>,  <6 * Days>,
             <Day>, <13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>,
       ...
        <0 * Days>, <13 * Days>, <13 * Days>, <13 * Days>, <13 * Days>,
       <13 * Days>, <13 * Days>, <13 * Days>,  <0 * Days>,  <0 * Days>],
      dtype='object', length=580551)

In [100]:
minute1 = pd.PeriodIndex(order3['ListingInfo1'],freq='T')
minute2 = pd.PeriodIndex(order3['UserupdateInfo2'],freq='T')
minute3 = pd.PeriodIndex(order1['Listinginfo1'],freq='T')
minute4 = pd.PeriodIndex(order1['LogInfo3'],freq='T')
timedelta_T1 = minute1 - minute2
timedelta_T2 = minute3 - minute4
print('用户信息更新表中的时间差为：\n',timedelta_T1)
print('登录信息表中的时间差为：\n',timedelta_T2)

用户信息更新表中的时间差为：
 Index([<18720 * Minutes>, <18720 * Minutes>, <18720 * Minutes>,
       <18720 * Minutes>, <18720 * Minutes>, <18720 * Minutes>,
       <18720 * Minutes>, <18720 * Minutes>, <18720 * Minutes>,
       <18720 * Minutes>,
       ...
       <18720 * Minutes>, <18720 * Minutes>, <18720 * Minutes>,
       <18720 * Minutes>, <18720 * Minutes>, <18720 * Minutes>,
       <18720 * Minutes>, <18720 * Minutes>, <18720 * Minutes>,
       <18720 * Minutes>],
      dtype='object', length=372463)
登录信息表中的时间差为：
 Index([<18720 * Minutes>, <14400 * Minutes>, <12960 * Minutes>,
       <11520 * Minutes>,  <8640 * Minutes>,  <1440 * Minutes>,
       <18720 * Minutes>, <18720 * Minutes>, <18720 * Minutes>,
       <18720 * Minutes>,
       ...
           <0 * Minutes>, <18720 * Minutes>, <18720 * Minutes>,
       <18720 * Minutes>, <18720 * Minutes>, <18720 * Minutes>,
       <18720 * Minutes>, <18720 * Minutes>,     <0 * Minutes>,
           <0 * Minutes>],
      dtype='object', length=580551)

# <center><size font=6.5>实训3

In [103]:
#掌握分组聚合的原理与步骤，掌握agg和apply聚合方法，掌握transform聚合方法
#分析用户信息更新表和登录信息表时，除了提取时间本身的信息外，还可以结合用户编号进行分组聚合，然后进行组内分析。通过组内分析可以得出每组组
#内的最早和最晚信息更新时间和登陆时间，登录次数和信息。
#用groupby方法对用户信息更新表和登录信息表进行分组
order1Group=order1[['Idx','LogInfo1','LogInfo2','Listinginfo1','LogInfo3']].groupby(by = 'Idx')
print("分组后的order1表为:",order1Group)
order2Group=order2[['Idx','UserInfo_1','UserInfo_2','UserInfo_3','UserInfo_4','WeblogInfo_1']].groupby(by = 'Idx')
print("分组后的order2表为:",order2Group)
order3Group=order3[['Idx','ListingInfo1','UserupdateInfo1','UserupdateInfo2']].groupby(by = 'Idx')
print("分组后的order3表为:",order3Group)

分组后的order1表为: <pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001EE470270F0>
分组后的order2表为: <pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001EE2C27E240>
分组后的order3表为: <pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001EE2C27E128>

In [104]:
#用agg方法求取分组后的最早和最晚更新及登录时间
print(order1[['LogInfo3']].agg(['min','max']))
print(order1[['Listinginfo1']].agg(['min','max']))
print(order3[['ListingInfo1']].agg(['min','max']))
print(order3[['UserupdateInfo2']].agg(['min','max']))
#第一次最早和最晚登录时间分别是2011-01-01，2014-11-10
#第二次最早和最晚登录时间分别是2013-11-01，2014-11-10
#第一次最早和最晚更新时间分别是2013-11-01，2014-11-10
#第二次最早和最晚更新时间分别是2012-09-01，2014-11-04

      LogInfo3
min 2011-01-01
max 2014-11-10
    Listinginfo1
min   2013-11-01
max   2014-11-10
    ListingInfo1
min   2013-11-01
max   2014-11-10
    UserupdateInfo2
min      2012-09-01
max      2014-11-04

In [105]:
#用size方法求取分组后的数据的信息更新次数与登录次数
print(order1[['LogInfo3']].agg(['size']))
print(order1[['Listinginfo1']].agg(['size']))
print(order3[['ListingInfo1']].agg(['size']))
print(order3[['UserupdateInfo2']].agg(['size']))
#第一次登录次数580551
#第二次登录次数580551
#第一次更新次数372463
#第二次更新次数372463
#虽然次数都没有变化，但是规模逐渐扩大，已经达到十万级别

      LogInfo3
size    580551
      Listinginfo1
size        580551
      ListingInfo1
size        372463
      UserupdateInfo2
size           372463

# <center><size font=6.5>实训4

In [106]:
#掌握透视表和交叉表的制作方法
#通过对数据的描述性统计，以及时间数据信息提取，分组聚合操作已经获得了相当多的信息，但用户信息更新表和登陆信息表是长表，
#而主表是宽表，需要通过长宽表转换将数据合并在一张以用户编号为主键的表内
#用pivot_table函数进行长宽表转换
order1Pivot = pd.pivot_table(order1[['Idx','LogInfo1','LogInfo2','Listinginfo1','LogInfo3']],index='Idx')
print(order1Pivot.head())

     LogInfo1  LogInfo2
Idx
3   -1.230769  5.153846
5   -1.272727  3.909091
8    2.096000  5.920000
12   5.864322  3.889447
16  -2.066667  4.333333

In [76]:
order2Pivot = pd.pivot_table(order2[['Idx','UserInfo_1','UserInfo_2','UserInfo_3','UserInfo_4','WeblogInfo_1']],index='Idx')
print(order2Pivot.head())

     UserInfo_1  UserInfo_3  WeblogInfo_1
Idx
3           5.0         5.0           NaN
5           1.0         3.0           NaN
8           3.0         4.0           NaN
12          1.0         3.0           NaN
16          1.0         4.0           NaN

In [117]:
# #出错点
# order4 = pd.read_csv('D:/Desktop/data/Training_Userupdate.csv',encoding='gbk')
# order3Pivot = pd.pivot_table(order4[['Idx','ListingInfo1','UserupdateInfo1','UserupdateInfo2']],index='Idx')
# print(order3Pivot.head())

DataError: No numeric types to aggregate

In [112]:
#用crosstab方法进行长宽转换
import numpy as np
ordercross1 = pd.crosstab(index = order1['Idx'],columns = order1['LogInfo1'],values = order1['LogInfo2'],aggfunc =np.sum,margins=True)
print(ordercross1.iloc[:5,:5])

LogInfo1   -10    -4    0     1      2
Idx
3          NaN   90.0  NaN   7.0    8.0
5         13.0   24.0  NaN   3.0    1.0
8         13.0  654.0  NaN   7.0   22.0
12        13.0  210.0  NaN  29.0  446.0
16         NaN   60.0  NaN   3.0    1.0

In [129]:
ordercross3 = pd.crosstab(index = order3['Idx'],columns = order3['ListingInfo1'],values = order3['UserupdateInfo1'],aggfunc =np.sum)
print(ordercross3)

ListingInfo1                                         2013-11-01  \
Idx
3                                                           NaN
5                                                           NaN
8                                                           NaN
12            _age_Age_EducationId_gender_HasBuyCar_idNumber...
16                                                          NaN
17                                                          NaN
18            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
20            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
21            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
23            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
29            _ByUserId_EducationId_HasBuyCar_IdNumber_LastU...
31                                                          NaN
33            _Age_flag_UCtoBcp_flag_UCtoBcp_flag_UCtoPVR_fl...
35                                                          NaN
36            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
37            _CompanyPhone_CompanyTypeId_EducationId_HasBuy...
41                                                          NaN
43                                                          NaN
48                                                          NaN
51                                                          NaN
57            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
62                                                          NaN
67                                                          NaN
68            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
71                                                          NaN
73            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
75                                                          NaN
80            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
81                                                          NaN
82            _CompanyAddress_CompanyName_CompanyPhone_Compa...
...                                                         ...
91610                                                       NaN
91613                                                       NaN
91617                                                       NaN
91618                                                       NaN
91620                                                       NaN
91626                                                       NaN
91628                                                       NaN
91630                                                       NaN
91635                                                       NaN
91642                                                       NaN
91643                                                       NaN
91646                                                       NaN
91647                                                       NaN
91660                                                       NaN
91666                                                       NaN
91668                                                       NaN
91670                                                       NaN
91672                                                       NaN
91674                                                       NaN
91676                                                       NaN
91677                                                       NaN
91680                                                       NaN
91681                                                       NaN
91686                                                       NaN
91688                                                       NaN
91689                                                       NaN
91693                                                       NaN
91695                                                       NaN
91702                                                       NaN
91703                                                       NaN

ListingInfo1                                         2013-11-04  \
Idx
3                                                           NaN
5                                                           NaN
8                                                           NaN
12                                                          NaN
16                                                          NaN
17                                                          NaN
18                                                          NaN
20                                                          NaN
21                                                          NaN
23                                                          NaN
29                                                          NaN
31                                                          NaN
33                                                          NaN
35                                                          NaN
36                                                          NaN
37                                                          NaN
41                                                          NaN
43            _CompanyPhone_EducationId_HasBuyCar_IdNumber_L...
48                                                          NaN
51                                                          NaN
57                                                          NaN
62                                                          NaN
67                                                          NaN
68                                                          NaN
71            _EducationId_EducationId_EducationId_HasBuyCar...
73                                                          NaN
75                                                          NaN
80                                                          NaN
81            _CompanyPhone_EducationId_HasBuyCar_IdNumber_L...
82                                                          NaN
...                                                         ...
91610                                                       NaN
91613                                                       NaN
91617                                                       NaN
91618                                                       NaN
91620                                                       NaN
91626                                                       NaN
91628                                                       NaN
91630                                                       NaN
91635                                                       NaN
91642                                                       NaN
91643                                                       NaN
91646                                                       NaN
91647                                                       NaN
91660                                                       NaN
91666                                                       NaN
91668                                                       NaN
91670                                                       NaN
91672                                                       NaN
91674                                                       NaN
91676                                                       NaN
91677                                                       NaN
91680                                                       NaN
91681                                                       NaN
91686                                                       NaN
91688                                                       NaN
91689                                                       NaN
91693                                                       NaN
91695                                                       NaN
91702                                                       NaN
91703                                                       NaN

ListingInfo1                                         2013-11-05  \
Idx
3             _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
5                                                           NaN
8                                                           NaN
12                                                          NaN
16            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
17            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
18                                                          NaN
20                                                          NaN
21                                                          NaN
23                                                          NaN
29                                                          NaN
31            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
33                                                          NaN
35            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
36                                                          NaN
37                                                          NaN
41                                                          NaN
43                                                          NaN
48                                                          NaN
51            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
57                                                          NaN
62            _EducationId_HasBuyCar_IdNumber_IncomeFrom_Las...
67                                                          NaN
68                                                          NaN
71                                                          NaN
73                                                          NaN
75            _age_educationId_gender_hasBuyCar_idNumber_Inc...
80                                                          NaN
81                                                          NaN
82                                                          NaN
...                                                         ...
91610                                                       NaN
91613                                                       NaN
91617                                                       NaN
91618                                                       NaN
91620                                                       NaN
91626                                                       NaN
91628                                                       NaN
91630                                                       NaN
91635                                                       NaN
91642                                                       NaN
91643                                                       NaN
91646                                                       NaN
91647                                                       NaN
91660                                                       NaN
91666                                                       NaN
91668                                                       NaN
91670                                                       NaN
91672                                                       NaN
91674                                                       NaN
91676                                                       NaN
91677                                                       NaN
91680                                                       NaN
91681                                                       NaN
91686                                                       NaN
91688                                                       NaN
91689                                                       NaN
91693                                                       NaN
91695                                                       NaN
91702                                                       NaN
91703                                                       NaN

ListingInfo1                                         2013-11-06  \
Idx
3                                                           NaN
5                                                           NaN
8             _EducationId_HasBuyCar_IdNumber_LastUpdateDate...
12                                                          NaN
16                                                          NaN
17                                                          NaN
18                                                          NaN
20                                                          NaN
21                                                          NaN
23                                                          NaN
29                                                          NaN
31                                                          NaN
33                                                          NaN
35                                                          NaN
36                                                          NaN
37                                                          NaN
41                                                          NaN
43                                                          NaN
48                                                          NaN
51                                                          NaN
57                                                          NaN
62                                                          NaN
67                                                          NaN
68                                                          NaN
71                                                          NaN
73                                                          NaN
75                                                          NaN
80                                                          NaN
81                                                          NaN
82                                                          NaN
...                                                         ...
91610                                                       NaN
91613                                                       NaN
91617                                                       NaN
91618                                                       NaN
91620                                                       NaN
91626                                                       NaN
91628                                                       NaN
91630                                                       NaN
91635                                                       NaN
91642                                                       NaN
91643                                                       NaN
91646                                                       NaN
91647                                                       NaN
91660                                                       NaN
91666                                                       NaN
91668                                                       NaN
91670                                                       NaN
91672                                                       NaN
91674                                                       NaN
91676                                                       NaN
91677                                                       NaN
91680                                                       NaN
91681                                                       NaN
91686                                                       NaN
91688                                                       NaN
91689                                                       NaN
91693                                                       NaN
91695                                                       NaN
91702                                                       NaN
91703                                                       NaN

ListingInfo1                                         2013-11-07 2013-11-08  \
Idx
3                                                           NaN        NaN
5             _EducationId_HasBuyCar_IdNumber_LastUpdateDate...        NaN
8                                                           NaN        NaN
12                                                          NaN        NaN
16                                                          NaN        NaN
17                                                          NaN        NaN
18                                                          NaN        NaN
20                                                          NaN        NaN
21                                                          NaN        NaN
23                                                          NaN        NaN
29                                                          NaN        NaN
31                                                          NaN        NaN
33                                                          NaN        NaN
35                                                          NaN        NaN
36                                                          NaN        NaN
37                                                          NaN        NaN
41            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...        NaN
43                                                          NaN        NaN
48                                                          NaN        NaN
51                                                          NaN        NaN
57                                                          NaN        NaN
62                                                          NaN        NaN
67            _EducationId_HasBuyCar_IdNumber_LastUpdateDate...        NaN
68                                                          NaN        NaN
71                                                          NaN        NaN
73                                                          NaN        NaN
75                                                          NaN        NaN
80                                                          NaN        NaN
81                                                          NaN        NaN
82                                                          NaN        NaN
...                                                         ...        ...
91610                                                       NaN        NaN
91613                                                       NaN        NaN
91617                                                       NaN        NaN
91618                                                       NaN        NaN
91620                                                       NaN        NaN
91626                                                       NaN        NaN
91628                                                       NaN        NaN
91630                                                       NaN        NaN
91635                                                       NaN        NaN
91642                                                       NaN        NaN
91643                                                       NaN        NaN
91646                                                       NaN        NaN
91647                                                       NaN        NaN
91660                                                       NaN        NaN
91666                                                       NaN        NaN
91668                                                       NaN        NaN
91670                                                       NaN        NaN
91672                                                       NaN        NaN
91674                                                       NaN        NaN
91676                                                       NaN        NaN
91677                                                       NaN        NaN
91680                                                       NaN        NaN

In [130]:
# ordercross3 = pd.crosstab(index = order3['Idx'],columns = order3['UserupdateInfo1'],values = order2['UserupdateInfo2'],aggfunc =np.sum,margins=True)
# print(ordercross3.iloc[:5,:5])
print(pd.concat([order2,order1Pivot,order2Pivot],axis=1,join='outer'))

           Idx  UserInfo_1  UserInfo_2  UserInfo_3  UserInfo_4  WeblogInfo_1  \
0      10001.0         1.0          深圳         4.0          深圳           NaN
1      10002.0         1.0          温州         4.0          温州           NaN
2      10003.0         1.0          宜昌         3.0          宜昌           NaN
3      10006.0         4.0          南平         1.0          南平           NaN
4      10007.0         5.0          辽阳         1.0          辽阳           NaN
5      10008.0         1.0          吴忠         5.0          银川           NaN
6      10011.0         1.0          绵阳         3.0          赤峰           NaN
7      10015.0         4.0          东莞         5.0          东莞           NaN
8      10019.0         1.0          赤峰         6.0          赤峰           NaN
9      10021.0         3.0          武汉         5.0          鄂州           NaN
10     10022.0         5.0          武汉         5.0          武汉           NaN
11     10024.0         5.0          长沙         5.0          长沙           NaN
12     10026.0         3.0          漳州         3.0          漳州           NaN
13     10027.0         3.0         牡丹江         6.0         牡丹江           NaN
14     10031.0         1.0          太原         3.0          太原           NaN
15     10032.0         1.0          北京         6.0          北京           NaN
16     10036.0         1.0          成都         3.0          忻州           NaN
17     10039.0         1.0          三明         4.0          三明           NaN
18     10040.0         1.0          临沂         6.0          临沂           NaN
19     10044.0         4.0          临沂         6.0          临沂           NaN
20     10050.0         1.0          福州         5.0          福州           NaN
21     10054.0         4.0          泰州         4.0          泰州           NaN
22     10059.0         5.0          成都         4.0          大同           NaN
23      1006.0         4.0          上海         5.0          上海           NaN
24     10063.0         1.0  红河哈尼族彝族自治州         5.0  红河哈尼族彝族自治州           NaN
25     10067.0         4.0          南平         4.0          南平           NaN
26     10068.0         1.0          郴州         5.0          郴州           NaN
27     10069.0         3.0          常州         4.0          常州           NaN
28      1007.0         6.0          湖州         6.0          湖州           NaN
29     10070.0         4.0          茂名         1.0          佛山           NaN
...        ...         ...         ...         ...         ...           ...
91610      NaN         NaN         NaN         NaN         NaN           NaN
91613      NaN         NaN         NaN         NaN         NaN           NaN
91617      NaN         NaN         NaN         NaN         NaN           NaN
91618      NaN         NaN         NaN         NaN         NaN           NaN
91620      NaN         NaN         NaN         NaN         NaN           NaN
91626      NaN         NaN         NaN         NaN         NaN           NaN
91628      NaN         NaN         NaN         NaN         NaN           NaN
91630      NaN         NaN         NaN         NaN         NaN           NaN
91635      NaN         NaN         NaN         NaN         NaN           NaN
91642      NaN         NaN         NaN         NaN         NaN           NaN
91643      NaN         NaN         NaN         NaN         NaN           NaN
91646      NaN         NaN         NaN         NaN         NaN           NaN
91647      NaN         NaN         NaN         NaN         NaN           NaN
91660      NaN         NaN         NaN         NaN         NaN           NaN
91666      NaN         NaN         NaN         NaN         NaN           NaN
91668      NaN         NaN         NaN         NaN         NaN           NaN
91670      NaN         NaN         NaN         NaN         NaN           NaN
91672      NaN         NaN         NaN         NaN         NaN           NaN
91674      NaN         NaN         NaN         NaN         NaN           NaN
91676      NaN         NaN         NaN         NaN         NaN           NaN
91677      NaN         NaN         NaN         NaN         NaN           NaN
91680      NaN         NaN         NaN         NaN         NaN           NaN
91681      NaN         NaN         NaN         NaN         NaN           NaN
91686      NaN         NaN         NaN         NaN         NaN           NaN
91688      NaN         NaN         NaN         NaN         NaN           NaN
91689      NaN         NaN         NaN         NaN         NaN           NaN
91693      NaN         NaN         NaN         NaN         NaN           NaN
91695      NaN         NaN         NaN         NaN         NaN           NaN
91702      NaN         NaN         NaN         NaN         NaN           NaN
91703      NaN         NaN         NaN         NaN         NaN           NaN

       WeblogInfo_2  WeblogInfo_3  WeblogInfo_4  WeblogInfo_5  ...  \
0               1.0           NaN           1.0           1.0  ...
1               0.0           NaN           1.0           1.0  ...
2               0.0           NaN           2.0           2.0  ...
3               NaN           NaN           NaN           NaN  ...
4               0.0           NaN           1.0           1.0  ...
5               0.0           NaN           2.0           2.0  ...
6               0.0           NaN          13.0           1.0  ...
7               0.0           NaN          12.0           6.0  ...
8               0.0           NaN          10.0           6.0  ...
9               0.0           NaN           1.0           1.0  ...
10              0.0           NaN           3.0           2.0  ...
11              1.0           NaN           1.0           1.0  ...
12              1.0           NaN          11.0           3.0  ...
13              0.0           NaN           1.0           1.0  ...
14              0.0           NaN           3.0           1.0  ...
15              0.0           NaN           2.0           2.0  ...
16              0.0           NaN           4.0           3.0  ...
17              0.0           NaN           4.0           2.0  ...
18              0.0           NaN           1.0           1.0  ...
19              0.0           NaN           2.0           2.0  ...
20              0.0           NaN           3.0           2.0  ...
21              0.0           NaN           3.0           2.0  ...
22              0.0           NaN           8.0           8.0  ...
23              1.0           NaN           1.0           1.0  ...
24              0.0           NaN           1.0           1.0  ...
25              0.0           NaN           2.0           1.0  ...
26              0.0           NaN           9.0           5.0  ...
27              0.0           NaN           2.0           2.0  ...
28              0.0           NaN           2.0           2.0  ...
29              0.0           NaN           2.0           1.0  ...
...             ...           ...           ...           ...  ...
91610           NaN           NaN           NaN           NaN  ...
91613           NaN           NaN           NaN           NaN  ...
91617           NaN           NaN           NaN           NaN  ...
91618           NaN           NaN           NaN           NaN  ...
91620           NaN           NaN           NaN           NaN  ...
91626           NaN           NaN           NaN           NaN  ...
91628           NaN           NaN           NaN           NaN  ...
91630           NaN           NaN           NaN           NaN  ...
91635           NaN           NaN           NaN           NaN  ...
91642           NaN           NaN           NaN           NaN  ...
91643           NaN           NaN           NaN           NaN  ...
91646           NaN           NaN           NaN           NaN  ...
91647           NaN           NaN           NaN           NaN  ...
91660           NaN           NaN           NaN           NaN  ...
91666           NaN           NaN           NaN           NaN  ...
91668           NaN           NaN           NaN           NaN  ...
91670           NaN           NaN           NaN           NaN  ...
91672           NaN           NaN           NaN           NaN  ...
91674           NaN           NaN           NaN           NaN  ...
91676           NaN           NaN           NaN           NaN  ...
91677           NaN           NaN           NaN           NaN  ...
91680           NaN           NaN           NaN           NaN  ...
91681           NaN           NaN           NaN           NaN  ...
91686           NaN           NaN           NaN           NaN  ...
91688           NaN           NaN           NaN           NaN  ...
91689           NaN           NaN           NaN           NaN  ...
91693           NaN           NaN           NaN           NaN  ...
91695           NaN           NaN           NaN           NaN  ...
91702           NaN           NaN           NaN           NaN  ...
91703           NaN           NaN           NaN           NaN  ...

       SocialNetwork_15  SocialNetwork_16  SocialNetwork_17  target  \
0                   0.0               0.0               1.0     0.0
1                   0.0               0.0               2.0     0.0
2                   0.0               0.0               0.0     0.0
3                   0.0               0.0               0.0     0.0
4                   0.0               0.0               0.0     0.0
5                   0.0               0.0               0.0     0.0
6                   0.0               0.0               1.0     1.0
7                   0.0               0.0               1.0     0.0
8                   0.0               1.0               0.0     1.0
9                   0.0               0.0               0.0     0.0
10                  0.0               0.0               0.0     0.0
11                  0.0               0.0               0.0     0.0
12                  0.0               0.0               1.0     0.0
13                  0.0               0.0               0.0     1.0
14                  0.0               0.0               1.0     0.0
15                  0.0               0.0               1.0     0.0
16                  0.0               0.0               0.0     0.0
17                  0.0               0.0               1.0     0.0
18                  0.0               0.0               0.0     1.0
19                  0.0               0.0               0.0     0.0
20                  0.0               0.0               1.0     0.0
21                  0.0               0.0               1.0     0.0
22                  0.0               0.0               1.0     0.0
23                  0.0               0.0               1.0     0.0
24                  0.0               0.0               0.0     0.0
25                  0.0               0.0               1.0     0.0
26                  0.0               0.0               1.0     0.0
27                  0.0               0.0               1.0     0.0
28                  1.0               0.0               0.0     0.0
29                  0.0               0.0               0.0     0.0
...                 ...               ...               ...     ...
91610               NaN               NaN               NaN     NaN
91613               NaN               NaN               NaN     NaN
91617               NaN               NaN               NaN     NaN
91618               NaN               NaN               NaN     NaN
91620               NaN               NaN               NaN     NaN
91626               NaN               NaN               NaN     NaN
91628               NaN               NaN               NaN     NaN
91630               NaN               NaN               NaN     NaN
91635               NaN               NaN               NaN     NaN
91642               NaN               NaN               NaN     NaN
91643               NaN               NaN               NaN     NaN
91646               NaN               NaN               NaN     NaN
91647               NaN               NaN               NaN     NaN
91660               NaN               NaN               NaN     NaN
91666               NaN               NaN               NaN     NaN
91668               NaN               NaN               NaN     NaN
91670               NaN               NaN               NaN     NaN
91672               NaN               NaN               NaN     NaN
91674               NaN               NaN               NaN     NaN
91676               NaN               NaN               NaN     NaN
91677               NaN               NaN               NaN     NaN
91680               NaN               NaN               NaN     NaN
91681               NaN               NaN               NaN     NaN
91686               NaN               NaN               NaN     NaN
91688               NaN               NaN               NaN     NaN
91689               NaN               NaN               NaN     NaN
91693               NaN               NaN               NaN     NaN
91695               NaN               NaN               NaN     NaN
91702               NaN               NaN               NaN     NaN
91703               NaN               NaN               NaN     NaN

       ListingInfo   LogInfo1  LogInfo2  UserInfo_1  UserInfo_3  WeblogInfo_1
0         2014/3/5        NaN       NaN         NaN         NaN           NaN
1        2014/2/26        NaN       NaN         NaN         NaN           NaN
2        2014/2/28        NaN       NaN         NaN         NaN           NaN
3        2014/2/25  -1.230769  5.153846         5.0         5.0           NaN
4        2014/2/27        NaN       NaN         NaN         NaN           NaN
5        2014/2/27  -1.272727  3.909091         1.0         3.0           NaN
6        2014/2/24        NaN       NaN         NaN         NaN           NaN
7        2014/2/28        NaN       NaN         NaN         NaN           NaN
8        2014/2/24   2.096000  5.920000         3.0         4.0           NaN
9        2014/2/27        NaN       NaN         NaN         NaN           NaN
10       2014/2/25        NaN       NaN         NaN         NaN           NaN
11        2014/3/6        NaN       NaN         NaN         NaN           NaN
12        2014/3/4   5.864322  3.889447         1.0         3.0           NaN
13       2014/2/26        NaN       NaN         NaN         NaN           NaN
14        2014/3/7        NaN       NaN         NaN         NaN           NaN
15       2014/2/26        NaN       NaN         NaN         NaN           NaN
16       2014/2/27  -2.066667  4.333333         1.0         4.0           NaN
17       2014/2/22  -1.363636  3.727273         1.0         3.0           NaN
18       2014/2/23  -2.794118  5.323529         5.0         5.0           NaN
19       2014/2/24        NaN       NaN         NaN         NaN           NaN
20       2014/2/26  -2.187500  4.437500         1.0         5.0           NaN
21       2014/2/24  -0.500000  6.285714         3.0         3.0           NaN
22       2014/2/26        NaN       NaN         NaN         NaN           NaN
23      2013/11/18  36.014925  5.716418         1.0         4.0           NaN
24       2014/2/22        NaN       NaN         NaN         NaN           NaN
25       2014/2/25        NaN       NaN         NaN         NaN           NaN
26        2014/3/4        NaN       NaN         NaN         NaN           NaN
27       2014/2/24        NaN       NaN         NaN         NaN           NaN
28      2013/11/18        NaN       NaN         NaN         NaN           NaN
29        2014/3/3  -2.157895  5.473684         1.0         5.0           NaN
...            ...        ...       ...         ...         ...           ...
91610          NaN  44.400000  8.350000         1.0         7.0           1.0
91613          NaN  46.785714  6.000000         3.0         5.0           NaN
91617          NaN  18.933333  6.266667         5.0         5.0           NaN
91618          NaN  -1.894737  6.210526         3.0         5.0           NaN
91620          NaN   1.833333  7.333333         1.0         5.0           NaN
91626          NaN  -0.923077  6.307692         3.0         6.0           NaN
91628          NaN  60.466667  9.133333         1.0         5.0           NaN
91630          NaN   3.771429  5.885714         1.0         3.0           NaN
91635          NaN  21.428571  7.142857         1.0         4.0           NaN
91642          NaN  -0.363636  6.363636         3.0         7.0           NaN
91643          NaN  53.600000  6.266667         3.0         5.0           NaN
91646          NaN  -0.529412  6.117647         3.0         5.0           NaN
91647          NaN  23.555556  6.777778         1.0         6.0           NaN
91660          NaN   1.833333  7.333333         3.0         5.0           NaN
91666          NaN  44.916667  6.375000         1.0         6.0           NaN
91668          NaN   1.000000  6.500000         1.0         5.0           NaN
91670          NaN  33.500000  6.192308         3.0         3.0           NaN
91672          NaN  27.857143  6.904762         4.0         5.0           NaN
91674          NaN   1.714286  6.571429         4.0         5.0           NaN
91676          NaN  56.272727  9.000000         4.0         6.0           NaN
91677          NaN  -0.562500  7.562500         1.0         4.0           NaN
91680          NaN  -1.708333  5.750000         5.0         3.0           NaN
91681          NaN   0.000000  6.400000         1.0         6.0           NaN
91686          NaN  57.058824  5.529412         3.0         5.0           NaN
91688          NaN  13.850000  6.950000         3.0         5.0           NaN
91689          NaN   1.714286  6.571429         4.0         5.0           NaN
91693          NaN   5.800000  6.733333         6.0         3.0           NaN
91695          NaN  29.150000  7.550000         3.0         6.0           NaN
91702          NaN   1.714286  6.571429         1.0         6.0           NaN
91703          NaN  27.190476  7.523810         6.0         5.0           NaN

[50462 rows x 233 columns]

# <center><font size=6.5>综述

In [ ]:
综合本文从P2P贷款数据，网贷用户的基本信息，用户登陆时间更新时间借款成交时间，以及这些时间的时间差揭示网络贷款不同用户的行为信息。账号是均
匀分布的，存款的人挺少的，但是存了款的人存了挺多钱，4分之1的人欠了钱，大部分人所得利息为6元，也有人是23元，
人们申请借款的时间分布是均匀的，借款审批间隔时间大部分是5天，最长7天。用户信息更新表和登录信息表中均存在大量时间
数据，提取时间数据内存在的信息，一方面可以加深对数据的理解另一方面能够探索这部分信息和目标的关联程
度。同时用户登录时间借款成交时间，用户信息更新时间这些时间的时间差也能够反映出P2P网络贷款不同用户的行为信息。
第一次最早和最晚登录时间分别是2011-01-01，2014-11-10
第二次最早和最晚登录时间分别是2013-11-01，2014-11-10
第一次最早和最晚更新时间分别是2013-11-01，2014-11-10
第二次最早和最晚更新时间分别是2012-09-01，2014-11-04
第一次登录次数580551
第二次登录次数580551
第一次更新次数372463
第二次更新次数372463
网贷中的更新活动都集中在2014年，而且是集中在第8，9，10周，并且都是最近登陆时间是第10周，第一次更新都在第8周，第二次更新都
在第10周，并且时间差都是13天
这些信息表明了2012年网贷活动已经开始频繁，而2014年就很活跃了，网贷平台大大加快了资金流通速度，这不仅仅是因为网络的快速便捷，
也因为2012年左右开始了移动互联网的建设，而正是这个时候，互联网进入下沉市场，大大扩展了市场的规模，而对于资金流通速度不够强的
下沉市场，确实需要快速审批的贷款平台。而存款数量过少表明大部分人的怀疑态度，不敢冒太大风险存入大量资金，也体现了网贷平台缺少
雄厚的资金实力。借款审批间隔较短，虽然次数都没有变化，但是规模逐渐扩大，已经达到十万级别